# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'
def shared_pods
    pod 'Alamofire', '~> 4.4'
    pod 'Unbox'
    pod 'Kingfisher'
    pod 'SVProgressHUD'
end

target 'OpenWeather' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!
  shared_pods
  # Pods for OpenWeather

  target 'OpenWeatherTests' do
    use_frameworks!
    shared_pods
    inherit! :search_paths
  
    # Pods for testing
  end

  target 'OpenWeatherUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
